---
# Must be run before any other apt task or else apt task will fail on missing auth
# This is only done on debian 12 and below, because since debian 13 the sources
# have changed, which requires another workaround later
- name: Remove automatically created VE Enterprise repo configuration
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    state: absent

- name: Set debian mirrors in /etc/apt/sources.list
  ansible.builtin.template:
    src: "system/apt/sources.list.j2"
    dest: "/etc/apt/sources.list"
    mode: "0644"
  register: _pve_debian_repo
  when: "pve_manage_debian_repository | bool"

- name: Trust Proxmox' packaging key on Debian < 12
  ansible.builtin.apt_key:
    data: "{{ lookup('file', pve_release_key) }}"
    id: "{{ pve_release_key_id }}"
    state: present
  when: "ansible_distribution_major_version | int < 12"

- name: Trust Proxmox' packaging key on Debian >= 12
  ansible.builtin.copy:
    src: "proxmox-release-{{ ansible_distribution_release }}.gpg"
    dest: "/etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release }}.gpg"
    mode: "0644"
  when: "ansible_distribution_major_version | int >= 12"

- name: Set the Proxmox apt source list file
  ansible.builtin.template:
    src: "system/apt/pve.list.j2"
    dest: "/etc/apt/sources.list.d/pve.list"
    backup: true
    mode: "0644"
    # validate: "apt-get update -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/%s"
  register: _pve_repo
  when: "ansible_distribution_major_version | int <= 12"

- name: Manage deb822 repositories
  block:
    - name: Add Proxmox repository
      ansible.builtin.deb822_repository:
        name: proxmox
        types: deb
        uris: "{{ pve_repository.uris }}"
        suites: "{{ pve_repository.suites }}"
        components: "{{ pve_repository.components }}"
        signed_by: /etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release }}.gpg
        state: present
      register: _pve_repo

    # Even when the no-subscription version is uses, the sources for the enterprise version
    # have to be defined in disabled state here. Otherwise this file is generated by a fresh proxmox
    # installation itself and fails with access denied error. Creating this file in disabled state
    # prevents this error-case
    - name: Add Proxmox enterprise repository
      ansible.builtin.deb822_repository:
        name: pve-enterprise
        types: deb
        uris: "{{ pve_repository.uris }}"
        suites: "{{ pve_repository.suites }}"
        components: "pve-enterprise"
        signed_by: /etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release }}.gpg
        state: present
        enabled: "{{ pve_enable_enterprise_repository }}"
      register: _pve_repo

    # comes from the original repository. Not used at the moment, but maybe usedful in the future
    # to make it consistent with the pve sources
    - name: Add Proxmox Ceph repository
      ansible.builtin.deb822_repository:
        name: ceph
        types: deb
        uris: "{{ pve_ceph_repository.uris }}"
        suites: "{{ pve_ceph_repository.suites }}"
        components: "{{ pve_ceph_repository.components }}"
        signed_by: /etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release }}.gpg
        state: present
      register: _pve_ceph_repo
      when: "pve_ceph_enabled | bool"

    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes
      when: _pve_repo is changed or _pve_ceph_repo is changed

  when: "ansible_distribution_major_version | int > 12"

- name: Set the Ceph apt source list file
  ansible.builtin.template:
    src: "system/apt/pve_ceph.list.j2"
    dest: "/etc/apt/sources.list.d/pve_ceph.list"
    backup: true
    mode: "0644"
    # validate: "apt-get update -o Dir::Etc::sourceParts=/etc/apt/sources.list.d/%s"
  register: _pve_ceph_repo
  when: "(pve_ceph_enabled | bool) or (pve_ceph_enhanced_enabled | bool)"

- name: Manage PVE-Kernel version pinning
  block:
    - name: Add PVE-Kernel pinning if defined
      ansible.builtin.template:
        src: "system/apt/pve-kernel-pin.j2"
        dest: "/etc/apt/preferences.d/proxmox-kernel-pin"
        mode: "0644"
      when: "pve_pin_kernel_version | default(false, true) is not false"

    - name: Remove PVE-Kernel pinning if not defined
      ansible.builtin.file:
        path: "/etc/apt/preferences.d/proxmox-kernel-pin"
        state: absent
      when: "pve_pin_kernel_version | default(false, true) is false"

- name: Ensure required packages for this role are installed
  ansible.builtin.apt:
    name:
      - gpg # needed for trusting keys in apt
      - python3-apt # required by Ansible
      - openssl # needed by ssl_config tasks
      - openvswitch-switch # needed for ovs-configuration
    state: present
    update_cache: true

- name: Remove disturbing packages before PVE install
  ansible.builtin.apt:
    name:
      - os-prober
      - linux-image-amd64
    state: absent

# workaround for vagrant-test-setup
- name: Hold grub-pc to avoid interactive prompt
  ansible.builtin.shell: |
    echo "grub-pc hold" | sudo dpkg --set-selections
  become: true
  when: "pve_vagrant_test_setup | bool"

- name: Perform safe upgrades on repo changes
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: "safe"
    allow_downgrade: true
  until: "_system_upgrade is succeeded"
  when:
    "_pve_debian_repo.changed | bool
    or _pve_repo.changed | bool
    or _pve_ceph_repo.changed | bool"
  retries: 3
  register: _system_upgrade

- name: Perform system dist upgrades if requested
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: "dist"
    allow_downgrade: true
  until: "_system_upgrade is succeeded"
  when: "pve_run_system_upgrades | bool"
  retries: 3
  register: _system_upgrade

- name: Install Proxmox VE and related packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ _pve_install_packages }}"
    state: "{{ 'latest' if pve_run_proxmox_upgrades else 'present' }}"
  until: "_proxmox_install is succeeded"
  retries: 2
  register: _proxmox_install

- name: Remove automatically created VE Enterprise repo source (again) after PVE install
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
    state: absent

# workaround for vagrant-test-setup
- name: Silence grub-pc device selection prompt
  ansible.builtin.debconf:
    name: grub-pc
    question: grub-pc/install_devices_empty
    value: "true"
    vtype: boolean
  when: "pve_vagrant_test_setup | bool"

- name: Remove unnecessary or unwanted apt packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ _pve_uninstall_packages }}"
    state: absent
    autoremove: true
    autoclean: true
    purge: true
  retries: 3
  register: _apt_uninstall
  until: "_apt_uninstall is succeeded"
  when: "_pve_uninstall_packages | default([]) | length > 0"

- name: Remove subscription check wrapper function in web UI
  ansible.builtin.lineinfile:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    line: '        orig_cmd(); return;'
    insertafter: '^\s+checked_command: function\(orig_cmd\) {$'
    firstmatch: true
    backup: true
  when: "pve_remove_subscription_warning | bool"
